### ISSUE TITLE
Network is unreachable - connect(2)

### ISSUE THREAD

**Issue by soylent** [jasmine/jasmine-gem#194]
When I run `rake jasmine:ci` the following exception is thrown (`Errno::ENETUNREACH`):

```
** Execute jasmine:require
** Invoke jasmine:configure (first_time)
** Execute jasmine:configure
** Execute jasmine:ci
rake aborted!
Network is unreachable - connect(2) for "localhost" port 42294
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/jasmine-2.0.0/lib/jasmine/base.rb:25:in `initialize'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/jasmine-2.0.0/lib/jasmine/base.rb:25:in `open'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/jasmine-2.0.0/lib/jasmine/base.rb:25:in `server_is_listening_on'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/jasmine-2.0.0/lib/jasmine/base.rb:35:in `wait_for_listener'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/jasmine-2.0.0/lib/jasmine/tasks/jasmine.rake:39:in `block (2 levels) in <top (required)>'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:236:in `call'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:236:in `block in execute'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:231:in `each'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:231:in `execute'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/opt/ruby/versions/2.1.0/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:161:in `invoke'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:149:in `invoke_task'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `each'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `block in top_level'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:115:in `run_with_threads'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:100:in `top_level'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:78:in `block in run'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/opt/ruby/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
bin/rake:4:in `<main>'
Tasks: TOP => jasmine:ci
```

I can send you a pull request for this issue, but I am not sure if this is a bug.
This problem occurs on CentOS Linux release 6.0 (Final)

**Comment by matchstick** [comment]
I was facing similar issue when using socket = TCPSocket.open(hostname, port) passing hostname as localhost. I found out actually the reason why the Errno::ENETUNREACH is raised is actually there was an IPV6 entry on my vm for localhost. After I removed the IPV6 line in /etc/hosts, the TCPSocket.open method works fine.
